language: android
sudo: required
jdk: oraclejdk8
 
 env:
 global:
 - ANDROID_API=28
 - EMULATOR_API=22
 - ANDROID_BUILD_TOOLS=28.0.3
 - ADB_INSTALL_TIMEOUT=5 # minutes
 
 android:
 components:
 - tools
 - platform-tools
 - build-tools-$ANDROID_BUILD_TOOLS
 - android-$ANDROID_API
 - android-$EMULATOR_API_LEVEL
 - extra-google-m2repository
 - extra-android-m2repository # for design library
 
 before_install:
- chmod +x gradlew


script:
- ./gradlew clean build connectedCheck -PdisablePreDex --stacktrace
