language: android
sudo: required
jdk: oraclejdk8
 
env:
 global:
  - ANDROID_API=28
  - ANDROID_BUILD_TOOLS=28.0.3
 
 android:
  components:
   - tools
   - platform-tools
   - build-tools-$ANDROID_BUILD_TOOLS
   - android-$ANDROID_API
 
before_install:
 - chmod +x gradlew

script:
 - ./gradlew clean build connectedCheck
